const loungeInfo = [
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/1.jpeg',
    address: '서울특별시 광진구 능동로 120 (화양동)',
    avgStars: 3.5,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/2.jpeg',
    address: '서울특별시 광진구 능동로 209 (군자동)',
    avgStars: 4.0,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/3.jpeg',
    address: '서울특별시 광진구 긴고랑로 131 (중곡동)',
    avgStars: 2.0,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/4.jpeg',
    address: '서울 광진구 아차산로 567',
    avgStars: 4.7,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/5.jpeg',
    address: '서울특별시 광진구 광나루로 480 (구의동)',
    avgStars: 2.8,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/6.jpeg',
    address: '서울특별시 광진구 자양로 167 (구의동)',
    avgStars: 1.9,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/1.jpeg',
    address: '서울특별시 광진구 구의강변로 38 (구의동)',
    avgStars: 2.5,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/2.jpeg',
    address: '서울특별시 광진구 능동로 90 (자양동)',
    avgStars: 3.2,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/3.jpeg',
    address: '서울특별시 광진구 동일로 156 (화양동)',
    avgStars: 3.8,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/4.jpeg',
    address: '서울특별시 광진구 동일로 172 (화양동)',
    avgStars: 2.8,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/5.jpeg',
    address: '서울특별시 광진구 동일로 90, 호텔케이월드 (자양동)',
    avgStars: 3.6,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/6.jpeg',
    address: '서울특별시 광진구 워커힐로 177 (광장동)',
    avgStars: 1.2,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/1.jpeg',
    address: '서울특별시 광진구 자양로 18길 26, 4층 (구의동)',
    avgStars: 4.6,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/2.jpeg',
    address: '서울특별시 광진구 천호대로 521 (중곡동)',
    avgStars: 2.5,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/3.jpeg',
    address: '서울특별시 광진구 천호대로 560 (능동)',
    avgStars: 4.2,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/4.jpeg',
    address: '서울특별시 광진구 자양로 165, 송곡회관 1층 (구의동)',
    avgStars: 2.5,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/5.jpeg',
    address: '서울특별시 광진구 자양로 283 (구의동)',
    avgStars: 3.3,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/6.jpeg',
    address: '서울특별시 광진구 광나루로 36길 56 (구의동)',
    avgStars: 3.7,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/1.jpeg',
    address: '서울특별시 광진구 자양로 117(자양동)',
    avgStars: 4.6,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/2.jpeg',
    address: '서울특별시 광진구 능동로 120 (화양동, 건국대학교)',
    avgStars: 1.6,
    comments: [],
  },
  {
    image: 'https://loungepic.s3.ap-northeast-2.amazonaws.com/3.jpeg',
    address: '서울특별시 광진구 강변역로 2 (구의동)',
    avgStars: 2.9,
    comments: [],
  },
]

export default loungeInfo
